#on:
#  push:
#    tags:
#      - "v*.*.*"

on: workflow_dispatch

name: build-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout tag
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          tag_name="${GITHUB_REF##*/}"
          echo Tag $tag_name
          git checkout $tag_name
          echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV

      - name: Build
        run: |
          make release -j$(nproc)
          
      - name: 查看结果文件
        run: |
          find build | xargs ls -ld
          
      - name: 查看版本
        run: |
          chmod 777 -R ${PWD}/build
          ${PWD}/build/linux-amd64/trojan-go -version
          
      - name: 上传文件Tencent Cloud COS Action
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: ${PWD}/build
          remote_path: trojan-go/${{ env.TAG_NAME }}
          clean: true
          
