#on:
#  push:
#    tags:
#      - "v*.*.*"

on: workflow_dispatch

name: build-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          make release -j$(nproc)
          
      - name: 设置ENV_ACTION_PATH值
        shell: bash
        run: echo "ENV_ACTION_PATH=$(echo ${PWD})" >> $GITHUB_ENV
        
      - name: 设置BRANCH_NAME
        shell: bash
        run: echo "ENV_BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
          
      - name: 查看结果文件
        run: |
          find build | xargs ls -ld
          
      - name: 查看版本
        run: |
          chmod 777 -R ${PWD}/build
          ${PWD}/build/linux-amd64/trojan-go -version
          
      - name: 上传文件darwin-amd64=>Tencent Cloud COS Action
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: ${{ env.ENV_ACTION_PATH }}/build/darwin-amd64
          remote_path: trojan-go/${{ env.ENV_BRANCH_NAME }}
          clean: false          #清空远程存储桶当前路径下的文件
          
      - name: 上传文件linux-amd64=>Tencent Cloud COS Action
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: ${{ env.ENV_ACTION_PATH }}/build/linux-amd64
          remote_path: trojan-go/${{ env.ENV_BRANCH_NAME }}
          clean: false         
          
      - name: 上传文件windows=>Tencent Cloud COS Action
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: ${{ env.ENV_ACTION_PATH }}/build/windows-amd64
          remote_path: trojan-go/${{ env.ENV_BRANCH_NAME }}
          clean: false         
          
          
          
          
          
          
          
          
