#on:
#  push:
#    tags:
#      - "v*.*.*"

on: workflow_dispatch

name: build-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout tag
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          tag_name="${GITHUB_REF##*/}"
          echo Tag $tag_name
          git checkout $tag_name
          echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV

      - name: Build
        run: |
          make release -j$(nproc)
          
      - name: LS
        run: |
          ls build
